[game]
hostname = "[RU][HRP] 🛡️ Aegis"
desc = """
⚠️ В данный момент сервер находится в состоянии альфа-теста!

🎭 Сервер с высоким уровнем ролевого отыгрыша.

🎮 Сервер включает в себя уникальные игровые механики билда Rayten, среди которых:
1. 📝 Создание предыстории персонажа! Позволяет создать уникального персонажа со своими особенностями и навыками.
2. 📚 Навыки персонажей! Масштабная система, о которой вам лучше прочитать на нашей вики...
3. 👮‍♀️ Система контрабанды!
4. 🎯 Цели отделов! Выполнение цели отдела даст вашему отделу премию от ЦК, окак.
5. 🔐 Переработка кодов угроз, их автоматическое снятие со временем, разделение на основные (красный, синий, зелёный) и дополнительные!
6. 📃 Система бюрократии позволяет заполнять документы в несколько кликов!
7. 🎉 Мини-игры для призраков!
8. ✨ И огромное количество прочих изменений, например самодельные оружия, авто-телепорт ядерного диска в космосе, верфь ДСО, скафандры защищают от шприцов и прочее, прочее
"""

map_pool = "VanillaMapPool"
soft_max_players = 45

[hub]
tags = "lang:ru,region:eu_e,rp:high"
advertise = true

[net]
port = 1213

[infolinks]
discord = "https://discord.gg/4ZqH5CuBGK"

