[server]
lobby_name = "Rayten — Aegis"
rules_file = "HRPRulset"

[game]
hostname = "🦖 RAYTEN — АЕГИС 🦖 | Новое комьюнити!"
desc = """
Мы открылись! Милости просим к нам в сообщество!

🎭 Сервер с высоким уровнем ролевого отыгрыша.

🎮 Сервер включает в себя уникальные игровые механики билда Rayten, среди которых:
1. 🎶 Голоса! Вместо ТТС текст персонажей озвучается их голосами, которые вы можете настроить. (как в undertale)
2. 📝 Создание предыстории персонажа! Позволяет создать уникального персонажа со своими особенностями и навыками.
3. 📚 Навыки персонажей! Масштабная система, о которой вам лучше прочитать на нашей вики...
4. 👮‍♀️ Система контрабанды!
5. 🎯 Цели отделов! Выполнение цели отдела даст вашему отделу премию от ЦК, окак.
6. 🔐 Переработка кодов угроз, их автоматическое снятие со временем, разделение на основные (красный, синий, зелёный) и дополнительные!
7. 📃 Система бюрократии позволяет заполнять документы в несколько кликов!
8. 🎉 Мини-игры для призраков!


✨ И огромное количество прочих изменений, например самодельные оружия, авто-телепорт ядерного диска в космосе, верфь ДСО, глушилки ядерных оперативников, механически блокирующие связь с ЦК, скафандры защищают от шприцов и прочее, факсы в другие сектора (верфь, цк) имеют задержку через блюспейс и прочее, прочее
"""
soft_max_players = 40

[hub]
tags = "lang:ru,region:eu_e,rp:med,rp:high"
hub_urls = "https://hub.fallback.spacestation14.com/"
advertise = true

[net]
tickrate = 30
max_connections = 80
port = 1213

[infolinks]
discord = "https://discord.gg/sRSGDyGPw2"
wiki = "https://rayten.ru/"
appeal = "https://discord.com/channels/1236324156165980311/1236381848909910126"
github = "https://github.com/RaytenCorp/Rayten"
bug_report = "https://discord.com/channels/1236324156165980311/1271239142944280671"
