[server]
lobby_name = "️Rayten — main"
[game]
hostname = "[MRP] ✨ Rayten ✨ | Собираем комьюнити | Новые механики [RU]"
desc = """
Добро пожаловать!

Сервер включает в себя множество новых механик, улучшающих геймплей, большинство правил переносятся в механики, а также у нас собственный каноничный сс13 лор!

У нас приятная атмосфера и адекватная администрация, открыт набор в команду администраторов проекта.

Станьте частью нашего комьюнити! ✨
"""
soft_max_players = 65

[hub]
tags = "lang:ru,region:eu_e,rp:med"
hub_urls = "https://hub.fallback.spacestation14.com/"
advertise = true

[net]
tickrate = 30
max_connections = 80
port = 1212

[infolinks]
discord = "https://discord.gg/sRSGDyGPw2"
wiki = "https://rayten.ru/"
appeal = "https://discord.com/channels/1236324156165980311/1236381848909910126"
github = "https://github.com/RaytenCorp/Rayten"
bug_report = "https://discord.com/channels/1236324156165980311/1271239142944280671"

