[server]
lobby_name = "️💎 Rayten 💎"
[game]
hostname = "[RU][MRP] 💎 Rayten"
desc = """
🎭 Сервер со средним уровнем ролевого отыгрыша.

🎮 Сервер включает в себя уникальные игровые механики билда Rayten, среди которых:
1. 🎶 Голоса! Вместо ТТС текст персонажей озвучается их голосами, которые вы можете настроить. (как в undertale)
2. 📝 Создание предыстории персонажа! Позволяет создать уникального персонажа со своими особенностями и навыками.
3. 📚 Навыки персонажей! Масштабная система, о которой вам лучше прочитать на нашей вики...
4. 👮‍♀️ Система контрабанды!
5. 🎯 Цели отделов! Выполнение цели отдела даст вашему отделу премию от ЦК, окак.
6. 🔐 Переработка кодов угроз, их автоматическое снятие со временем, разделение на основные (красный, синий, зелёный) и дополнительные!
7. 📃 Система бюрократии позволяет заполнять документы в несколько кликов!
8. 🎉 Мини-игры для призраков!
9. ✨ И огромное количество прочих изменений, например самодельные оружия, авто-телепорт ядерного диска в космосе, верфь ДСО, скафандры защищают от шприцов и прочее, прочее
"""
map_pool = "VanillaMapPool"
panic_bunker.enabled = false
contraband_examine = false
lobbyenabled = true
lobbyduration = 180
round_restart_time = 180
soft_max_players = 65

[hub]
tags = "lang:ru,region:eu_e,rp:med"
hub_urls = "https://hub.fallback.spacestation14.com/"
advertise = true

[net]
tickrate = 30
max_connections = 80
port = 1212

[infolinks]
discord = "https://discord.gg/sRSGDyGPw2"
wiki = "https://rayten.ru/"
appeal = "https://discord.com/channels/1236324156165980311/1236381848909910126"
github = "https://github.com/RaytenCorp/Rayten"
bug_report = "https://discord.com/channels/1236324156165980311/1271239142944280671"

