[game]
hostname = "[RU][MRP] 🛡️ Rayten"
desc = """
🎭 Сервер со средним уровнем ролевого отыгрыша.

🎮 Сервер включает в себя уникальные игровые механики билда Rayten, среди которых:
1. 📝 Создание предыстории персонажа! Позволяет создать уникального персонажа со своими особенностями и навыками.
2. 📚 Навыки персонажей! Масштабная система, о которой вам лучше прочитать на нашей вики...
3. 👮‍♀️ Система контрабанды!
4. 🎯 Цели отделов! Выполнение цели отдела даст вашему отделу премию от ЦК, окак.
5. 🔐 Переработка кодов угроз, их автоматическое снятие со временем, разделение на основные (красный, синий, зелёный) и дополнительные!
6. 📃 Система бюрократии позволяет заполнять документы в несколько кликов!
7. 🎉 Мини-игры для призраков!
8. ✨ И огромное количество прочих изменений, например самодельные оружия, авто-телепорт ядерного диска в космосе, верфь ДСО, скафандры защищают от шприцов и прочее, прочее
"""
map_pool = "VanillaMapPool"
soft_max_players = 65

[hub]
tags = "lang:ru,region:eu_e,rp:med"
advertise = true

[net]
port = 1212

[infolinks]
discord = "https://discord.gg/sRSGDyGPw2"
wiki = "https://rayten.ru/"
appeal = "https://discord.com/channels/1236324156165980311/1236381848909910126"
github = "https://github.com/RaytenCorp/Rayten"
bug_report = "https://discord.com/channels/1236324156165980311/1271239142944280671"

