- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 9000 #2.5 hrs
    - !type:AgeRequirement
      requiredAge: 22 # Vanilla
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 0
        MedicineLevel: 3
        ChemistryLevel: 3
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        Atmosphere: true
        Piloting: false
        MusInstruments: true
        Botany: false
        Bureaucracy: true
      - type: AddSkillPoints
        Points: 1
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff
